name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Neo4j Cypher-DSL
    runs-on: ubuntu-latest
    outputs:
      revision: ${{ steps.revision_step.outputs.revision }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
      - name: Determine revision
        id: revision_step
        run: |
          REVISION=$(./bin/extract-version.sh)
          echo "REVISION=$REVISION" >> $GITHUB_ENV
          echo "OLD_VERSION=$(./bin/extract-version.sh latest)" >> $GITHUB_ENV
          echo "::set-output name=revision::$REVISION"
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Maven build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./mvnw --no-transfer-progress clean deploy -DSCHEMA_NAMES_TEST_ALL_VERSIONS=true -P-sonar -Drevision=$REVISION -Dsha1=-$GITHUB_SHA -Dchangelist= -Dcypher-dsl.version.old=$OLD_VERSION
          -DaltDeploymentRepository=releases::default::file://$GITHUB_WORKSPACE/target/repository -DskipTests
          -pl !org.neo4j:neo4j-cypher-dsl-native-tests
          -pl !org.neo4j:neo4j-cypher-dsl-examples-core
          -pl !org.neo4j:neo4j-cypher-dsl-examples-parser
          -pl !org.neo4j:neo4j-cypher-dsl-examples-sdn6
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/repository
